### ISSUE TITLE
Not a directory when trying to look for TRT models

### ISSUE THREAD

**Issue by arcanite24** [VoltaML/voltaML-fast-stable-diffusion#25]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/workspace/voltaML-fast-stable-diffusion/app.py", line 155, in scan_directory
    tmp2 = os.listdir(os.path.join(trt_model_path,i))
NotADirectoryError: [Errno 20] Not a directory: 'engine/unet_fp16.plan'`

**Comment by VoltaML** [comment]
Please create a directory called 'engine' before you run the acceleration

**Comment by arcanite24** [comment]
Where do I need to create the engine folder?
I currently have this two folders:
c:/voltaml/engine
c:/voltaml/output

and I'm running the container with the following command:
`docker run --gpus=all -v C:\voltaml\engine/engine:/workspace/voltaML-fast-stable-diffusion/engine -v C:\voltaml\output/engine:/workspace/voltaML-fast-stable-diffusion/static/output -p 5003:5003 -it voltaml/volta_diffusion_webui:v0.2`

**Comment by arktronic** [comment]
The issue appears to be that plan files are created in multiple locations, and the app code can't handle them being directly in `/engine`. If you see other `*.plan` files under `/engine/[modelowner]/[modelname]/`, then try deleting the plan files that are inside the `engine` directory itself.
