### ISSUE TITLE
Docker gets stuck

### ISSUE THREAD

**Issue by RaymondTracer** [VoltaML/voltaML-fast-stable-diffusion#34]
I get stuck at `Volume "voltaml-fast-stable-diffusion_output"  Creating`

I use Windows 10 64-bit.

**Comment by RaymondTracer** [comment]
I took a look at the docker log, it repeats this error over and over again:

```
[2023-02-01T12:38:32.644566900Z][IPCServer][E] (1e6eec0e) 894b4f73-CSharpAPI S->C 039eb55c-ProxyPKG POST /filesharing/prompt (65ms): Internal Server Error
[2023-02-01T12:38:32.645567300Z][com.docker.proxy.exe][W] (1e6eec0e) 039eb55c-ProxyPKG C<-S 894b4f73-CSharpAPI POST /filesharing/prompt (163.996ms): status code not OK but 500:     ÿÿÿÿ          "System.UnauthorizedAccessException   	ClassNameMessageDataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteStackIndexExceptionMethodHResultSource
[2023-02-01T12:38:32.647565800Z][ApiProxy][I] WatsonBuckets  System.Collections.IDictionarySystem.Exception   "System.UnauthorizedAccessException   GAccess is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
[2023-02-01T12:38:32.647565800Z][ApiProxy][I]       at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
[2023-02-01T12:38:32.647565800Z][ApiProxy][I]    at Docker.WPF.PromptShareDirectory.<PromptUserAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.WPF\PromptShareDirectory.cs:line 53
[2023-02-01T12:38:32.647565800Z][ApiProxy][I] --- End of stack trace from previous location where exception was thrown ---
[2023-02-01T12:38:32.647565800Z][ApiProxy][I]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-01T12:38:32.647565800Z][ApiProxy][I]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at Docker.HttpApi.Controllers.FilesharingController.<Prompt>d__3.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 27
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] --- End of stack trace from previous location where exception was thrown ---
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] --- End of stack trace from previous location where exception was thrown ---
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] --- End of stack trace from previous location where exception was thrown ---
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] --- End of stack trace from previous location where exception was thrown ---
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]    at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
[2023-02-01T12:38:32.648067700Z][ApiProxy][I]        Ɂ8
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] Show
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] Windows.UI.Notifications.ToastNotifier
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] Void Show(Windows.UI.Notifications.ToastNotification)    
[2023-02-01T12:38:32.648067700Z][ApiProxy][I] Windows.UI
[2023-02-01T12:38:33.658068300Z][com.docker.proxy.exe][I] (1e6eec0e-1) 039eb55c-ProxyPKG C->S CSharpAPI POST /filesharing/prompt: {"path":"C:\\voltaml\\output"}
[2023-02-01T12:38:33.753572600Z][IPCServer][I] (1e6eec0e-1) 894b4f73-CSharpAPI S<-C 039eb55c-ProxyPKG POST /filesharing/prompt
github.com/docker/pinata/common/pkg/gui.(*guiClient).Prompt(0xc000587880, {0xc0006281cc, 0x11})
	github.com/docker/pinata/common/pkg/gui/client_windows.go:56 +0xb1
github.com/docker/pinata/common/pkg/proxy.ShareUserAsker.VerifyIsShared({0xc000536320, {0x1315420, 0xc000536280}, {0x1312a08, 0xc000587880}}, {0xc000628180, 0x11})
	github.com/docker/pinata/common/pkg/proxy/mounts_windows.go:171 +0x112
github.com/docker/pinata/common/pkg/proxy.(*WindowsMountRewriter).RewriteMount(0xc00036c600, {{0x11cc649, 0x4}, {0xc0006280d8, 0x11}, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...})
	github.com/docker/pinata/common/pkg/proxy/mounts_windows.go:71 +0x298
github.com/docker/pinata/common/pkg/proxy.(*proxyVolumeCreate).rewriteVolumeCreate(0xc000008138, 0xc00036d1a0)
	github.com/docker/pinata/common/pkg/proxy/volumes.go:75 +0x2b8
github.com/docker/pinata/common/pkg/proxy.(*proxyVolumeCreate).RequestRewrite(0x9864fc?, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/volumes.go:35 +0x18b
github.com/docker/pinata/common/pkg/proxy.(*passthrough).doHandleHTTP(0xc00008e960, {0x1d3f4c3d600?, 0xc000080820}, {0x1309680?, 0xc0002cc1c0}, 0x2?, {0x2?, 0xc00054f518?, 0x1820a20?})
	github.com/docker/pinata/common/pkg/proxy/passthrough.go:185 +0x104
github.com/docker/pinata/common/pkg/proxy.(*passthrough).HandleHTTP(0xc00008e960, {0x1309680, 0xc0002cc1c0}, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/passthrough.go:120 +0x432
github.com/docker/pinata/common/pkg/proxy.withError.func1({0x1309680, 0xc0002cc1c0}, 0xc00054f598?)
	github.com/docker/pinata/common/pkg/proxy/routes.go:16 +0x3c
github.com/docker/pinata/common/pkg/proxy.NewRouter.func2.1({0x1309680, 0xc0002cc1c0}, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/proxy.go:108 +0x2fd
github.com/docker/pinata/common/pkg/proxy.NewRouter.func1.1({0x1309680, 0xc0002cc1c0}, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/proxy.go:77 +0x142
github.com/docker/pinata/common/pkg/proxy.(*restrictions).Middleware.func1({0x1309680, 0xc0002cc1c0}, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/restrictions.go:73 +0x157
github.com/docker/pinata/common/pkg/proxy.(*BackendAnalytics).Middleware.func1({0x1309680, 0xc0002cc1c0}, 0xc00016c900)
	github.com/docker/pinata/common/pkg/proxy/analytics.go:61 +0xac
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00036e0c0, {0x1309680, 0xc0002cc1c0}, 0xc00016c700)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
[2023-02-01T12:38:33.758568700Z][IPCServer][E] (1e6eec0e-1) 894b4f73-CSharpAPI S->C 039eb55c-ProxyPKG POST 
```

**Comment by Stax124** [comment]
We had a release yesterday and it seems that windows is working correctly now, can you please try following the steps in our documentation, if issue persists, please send more info.

If this fixes your issue, please close it.

**Comment by RaymondTracer** [comment]
Still getting an error:
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

**Comment by Stax124** [comment]
That means that you have WSL1, not WSL2, please refer to official Microsoft guide on how to switch.

Only WSL2 allows GPU support.

**Comment by Stax124** [comment]
Check other distros, I think that docker is using their own distro, not Ubuntu

**Comment by RaymondTracer** [comment]
Still not working
```
PS C:\Users\user\Documents\GitHub\voltaML-fast-stable-diffusion> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop
docker-desktop-data
PS C:\Users\user\Documents\GitHub\voltaML-fast-stable-diffusion> wsl --set-version docker-desktop 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.
PS C:\Users\user\Documents\GitHub\voltaML-fast-stable-diffusion> wsl --set-version docker-desktop-data 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.
PS C:\Users\user\Documents\GitHub\voltaML-fast-stable-diffusion> docker compose run --service-ports voltaml
>>
[+] Running 1/1
 - voltaml Pulled                                                                                                  2.3s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
PS C:\Users\user\Documents\GitHub\voltaML-fast-stable-diffusion>
```

**Comment by RaymondTracer** [comment]
Seems nothing is working, I think we need a docker container for running docker. Maybe a future commit will make it work.

**Comment by Stax124** [comment]
I have no idea what should that mean, there are multiple people that have it working totally fine, both Windows and Linux. There is nothing that can be fixed. This is probably problem with your system.

You can try running this to check:
`docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04`

This is official Nvidia image, if this doesn't work, then you don't have GPU support enabled for Docker

**Comment by RaymondTracer** [comment]
>I have no idea what should that mean
Sorry, that was a bad attempt at sarcasm.

I'm not sure what the issue is at this point, even with that command it refuses to run, I'll look into more later, maybe Volta might know something that could help? At least A1111's SD works for now, but I was really looking forward to giving this a go.

**Comment by Stax124** [comment]
> > I have no idea what should that mean
> 
> Sorry, that was a bad attempt at sarcasm.
> 
> I'm not sure what the issue is at this point, even with that command it refuses to run, I'll look into it more later, maybe Volta might know something that could help? At least A1111's SD works for now, but I was really looking forward to giving this a go.

I will be creating a WSL guide for people that cannot use Docker (should be up by the weekend I hope). This issue seems to be something with your rig (or config) as most of the people were able to run it. I hope that this will give you a chance to run it as well. Closing this issue for now.
