### ISSUE TITLE
image to image AND controlnet don't work when use AIT model

### ISSUE THREAD

**Issue by brucelil** [VoltaML/voltaML-fast-stable-diffusion#57]
INFO:     172.18.22.48:57122 - "POST /api/generate/img2img HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/core/cluster.py", line 143, in generate
    return await best_gpu.generate(job)
  File "/app/core/gpu.py", line 135, in generate
    raise err
  File "/app/core/gpu.py", line 127, in generate
    images = await run_in_thread_async(func=generate_thread_call, args=(job,))
  File "/app/core/utils.py", line 77, in run_in_thread_async
    raise exc
  File "/app/core/thread.py", line 45, in run
    self._return = target(*self._args, **self._kwargs)  # type: ignore
  File "/app/core/gpu.py", line 93, in generate_thread_call
    images: List[Image.Image] = model.generate(job)
  File "/app/core/inference/aitemplate.py", line 102, in generate
    images = self.img2img(job)
  File "/app/core/inference/aitemplate.py", line 176, in img2img
    pipe = StableDiffusionImg2ImgAITPipeline(
  File "/app/core/aitemplate/src/ait_img2img.py", line 111, in __init__
    self.clip_ait_exe = self.init_ait_module(
  File "/app/core/aitemplate/src/ait_img2img.py", line 137, in init_ait_module
    mod = Model(os.path.join(workdir, model_name, "test.so"))
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 213, in __init__
    self.DLL = self._DLLWrapper(lib_path)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 164, in __init__
    self.DLL = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: tmp/CLIPTextModel/test.so: cannot open shared object file: No such file or directory

**Comment by brucelil** [comment]
ok，I think i should try new docker images，/app/core/aitemplate/src/ait_img2img.py  this file is a old version

**Comment by Stax124** [comment]
It seems that you are on the main branch which is really outdated.

Docker is outdated and not really recommend as WSL is probably simpler and faster to get up and running assuming that you are on Windows.

**Comment by brucelil** [comment]
had tested experimental ，image to image work well，but controlnet got RuntimeError:
08:19:26 | core.inference.aitemplate | INFO » Done loading controlnet unet
08:19:27 | core.inference.aitemplate | INFO » Optimization: Enabled xformers memory efficient attention
  4%|████████▊                                                                                                                                                                                                                   | 1/25 [00:02<00:50,  2.11s/it]
INFO:     172.18.22.48:53068 - "POST /api/generate/controlnet HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/api/routes/generate.py", line 140, in controlnet_job
    images, time = await gpu.generate(job)
  File "/app/core/gpu.py", line 219, in generate
    raise e
  File "/app/core/gpu.py", line 181, in generate
    raise err
  File "/app/core/gpu.py", line 167, in generate
    generated_images = await run_in_thread_async(
  File "/app/core/utils.py", line 102, in run_in_thread_async
    raise exc
  File "/app/core/thread.py", line 45, in run
    self._return = target(*self._args, **self._kwargs)  # type: ignore
  File "/app/core/gpu.py", line 107, in generate_thread_call
    images: List[Image.Image] = model.generate(job)
  File "/app/core/inference/aitemplate.py", line 220, in generate
    images = self.controlnet2img(job)
  File "/app/core/inference/aitemplate.py", line 399, in controlnet2img
    data = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/core/aitemplate/src/ait_controlnet.py", line 459, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 514, in forward
    sample = self.conv_in(sample)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

**Comment by Stax124** [comment]
Did you recompile the model? It needs recompiled UNet.

I do not test Docker, so I can't even tell you that ControlNet is fully operational. Smoke tests are only ran on local instances.

**Comment by brucelil** [comment]
> Did you recompile the model? It needs recompiled UNet.
> 
> I do not test Docker, so I can't even tell you that ControlNet is fully operational. Smoke tests are only ran on local instances.
yes ,I had recompile model,:
1.8G    /opt/data/aitemplate/runwayml--stable-diffusion-v1-5__512x512x1/ControlNetUNet2DConditionModel
159M    /opt/data/aitemplate/runwayml--stable-diffusion-v1-5__512x512x1/AutoencoderKL
1.8G    /opt/data/aitemplate/runwayml--stable-diffusion-v1-5__512x512x1/UNet2DConditionModel
240M    /opt/data/aitemplate/runwayml--stable-diffusion-v1-5__512x512x1/CLIPTextModel

then ,I try rebuild docker images  with experimental branch today，controlnet can't work neither  pytorch model nor ait model now,

PYTORCH model logs:

04:11:36 | root | INFO » Adding job 30f00bc7-a812-4326-85e5-8fb86a9f6c5f to queue
04:11:38 | core.inference.pytorch | INFO » Optimization: Enabled xformers memory efficient attention
INFO:     172.18.22.48:64109 - "POST /api/generate/controlnet HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2992, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3, 3), '|u1')


AIT model logs:

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 23.00it/s]
INFO:     172.18.22.48:63413 - "POST /api/generate/img2img HTTP/1.1" 200 OK
04:07:10 | root | INFO » Adding job d1d06e64-c09d-47b3-974b-abb5a6af5e12 to queue
04:07:11 | core.inference.aitemplate | INFO » Loading controlnet unet
[04:07:12] model_container.cu:67: Device Runtime Version: 11080; Driver Version: 12000
[04:07:12] model_container.cu:81: Hardware accelerator device properties: 
  Device: 
     ASCII string identifying device: NVIDIA A10
     Major compute capability: 8
     Minor compute capability: 6
     UUID: GPU-70b6cbcb-1e83-5785-e984-fa2f8d326937
     Unique identifier for a group of devices on the same multi-GPU board: 0
     PCI bus ID of the device: 0
     PCI device ID of the device: 4
     PCI domain ID of the device: 0
  Memory limits: 
     Constant memory available on device in bytes: 65536
     Global memory available on device in bytes: 23676715008
     Size of L2 cache in bytes: 6291456
     Shared memory available per block in bytes: 49152
     Shared memory available per multiprocessor in bytes: 102400
[04:07:12] model_container.cu:85: Init AITemplate Runtime with 1 concurrency
04:07:12 | core.inference.aitemplate | INFO » Done loading controlnet unet
04:07:14 | core.inference.aitemplate | INFO » Optimization: Enabled xformers memory efficient attention
INFO:     172.18.22.48:63488 - "POST /api/generate/controlnet HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2992, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3, 3), '|u1')
