### ISSUE TITLE
Websockets connection  sudden break  when set "batch count" more than 1

### ISSUE THREAD

**Issue by brucelil** [VoltaML/voltaML-fast-stable-diffusion#58]
logs:
02:10:14 | root | INFO » Adding job e2ffa91a-e182-45ca-a93b-6112251cbd6c to queue
100% 25/25 [00:01<00:00, 17.57it/s]
100% 25/25 [00:01<00:00, 17.52it/s]
100% 25/25 [00:01<00:00, 17.43it/s]
100% 25/25 [00:01<00:00, 17.46it/s]
100% 25/25 [00:01<00:00, 17.43it/s]
100% 25/25 [00:01<00:00, 17.23it/s]
100% 25/25 [00:01<00:00, 17.40it/s]
100% 25/25 [00:01<00:00, 17.42it/s]
100% 25/25 [00:01<00:00, 17.32it/s]
INFO:     172.18.22.48:62843 - "POST /api/generate/txt2img HTTP/1.1" 200 OK
02:10:33 | asyncio | ERROR » Task exception was never retrieved
future: <Task finished name='Task-4' coro=<WebSocketManager.perf_loop() done, defined at /app/api/websockets/manager.py:32> exception=ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), True)>
Traceback (most recent call last):
  File "/app/api/websockets/manager.py", line 60, in perf_loop
    await self.broadcast(Data(data_type="cluster_stats", data=data))
  File "/app/api/websockets/manager.py", line 83, in broadcast
    await connection.send_json(data.to_json())
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 173, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
ERROR:    Exception in ASGI application

**Comment by Stax124** [comment]
Can you check if it's the same on the Experimental branch?

**Comment by brucelil** [comment]
> Can you check if it's the same on the Experimental branch?

I will do more try，currently not reproduced
